### ISSUE TITLE
Shadow Grey buttons doest work

### ISSUE THREAD

**Issue by DavidEnds** [ttnmapper/ttnmapper-android-v3#3] opened 2018-12-11 08:40 UTC
Buttons like "log in to TTN and choose a device" doest work in Android 8

**Comment by jpmeijers** [comment] 2018-12-11 08:45
Yes, that is the intended behaviour. Greyed out buttons are features that are still a work in progress. If you kept an eye on these items during the past few updates you would have been able to see how features were being added. 

The only big one that is currently missing is the login to TTN to choose a device feature. It's low priority as the same can be done using the TTN Mobile app and choosing the "Use with TTN Mapper" option.

The other incomplete feature is "auto zoom". It's still debatable if this is useful and if it should not be combined with "auto centre".

**Comment by jpmeijers** [comment] 2018-12-12 14:56
Fixed in latest release: https://github.com/ttnmapper/ttnmapper-android-v3/commit/8773b8c4eefc0da4f70552794c809509a6e23779

**Closed as completed by jpmeijers** 2018-12-12 14:56 UTC
